package cn.xpms.third.security.dao.generator.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class PublicSecurityUploadInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.id
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.order_no
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.card_type
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.credential_no
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String credentialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.name
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.sex
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.nation
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.birthday
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.credential_valid_start
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String credentialValidStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.credential_valid_end
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String credentialValidEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.address
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.phone
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.hotel_code
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String hotelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.room_no
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String roomNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.credential_image
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String credentialImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.face_image
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String faceImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.verify_result
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String verifyResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.verify_score
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String verifyScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.checkin_time
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date checkinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.checkin_upload
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String checkinUpload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.checkout_time
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date checkoutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.checkout_upload
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String checkoutUpload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.param_ext
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String paramExt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.valid
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.create_user
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.create_time
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.modify_user
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.modify_time
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_info.memo
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", cardType=").append(cardType);
        sb.append(", credentialNo=").append(credentialNo);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", nation=").append(nation);
        sb.append(", birthday=").append(birthday);
        sb.append(", credentialValidStart=").append(credentialValidStart);
        sb.append(", credentialValidEnd=").append(credentialValidEnd);
        sb.append(", address=").append(address);
        sb.append(", phone=").append(phone);
        sb.append(", hotelCode=").append(hotelCode);
        sb.append(", roomNo=").append(roomNo);
        sb.append(", credentialImage=").append(credentialImage);
        sb.append(", faceImage=").append(faceImage);
        sb.append(", verifyResult=").append(verifyResult);
        sb.append(", verifyScore=").append(verifyScore);
        sb.append(", checkinTime=").append(checkinTime);
        sb.append(", checkinUpload=").append(checkinUpload);
        sb.append(", checkoutTime=").append(checkoutTime);
        sb.append(", checkoutUpload=").append(checkoutUpload);
        sb.append(", paramExt=").append(paramExt);
        sb.append(", valid=").append(valid);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", memo=").append(memo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PublicSecurityUploadInfo other = (PublicSecurityUploadInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getCardType() == null ? other.getCardType() == null : this.getCardType().equals(other.getCardType()))
            && (this.getCredentialNo() == null ? other.getCredentialNo() == null : this.getCredentialNo().equals(other.getCredentialNo()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getNation() == null ? other.getNation() == null : this.getNation().equals(other.getNation()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getCredentialValidStart() == null ? other.getCredentialValidStart() == null : this.getCredentialValidStart().equals(other.getCredentialValidStart()))
            && (this.getCredentialValidEnd() == null ? other.getCredentialValidEnd() == null : this.getCredentialValidEnd().equals(other.getCredentialValidEnd()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getHotelCode() == null ? other.getHotelCode() == null : this.getHotelCode().equals(other.getHotelCode()))
            && (this.getRoomNo() == null ? other.getRoomNo() == null : this.getRoomNo().equals(other.getRoomNo()))
            && (this.getCredentialImage() == null ? other.getCredentialImage() == null : this.getCredentialImage().equals(other.getCredentialImage()))
            && (this.getFaceImage() == null ? other.getFaceImage() == null : this.getFaceImage().equals(other.getFaceImage()))
            && (this.getVerifyResult() == null ? other.getVerifyResult() == null : this.getVerifyResult().equals(other.getVerifyResult()))
            && (this.getVerifyScore() == null ? other.getVerifyScore() == null : this.getVerifyScore().equals(other.getVerifyScore()))
            && (this.getCheckinTime() == null ? other.getCheckinTime() == null : this.getCheckinTime().equals(other.getCheckinTime()))
            && (this.getCheckinUpload() == null ? other.getCheckinUpload() == null : this.getCheckinUpload().equals(other.getCheckinUpload()))
            && (this.getCheckoutTime() == null ? other.getCheckoutTime() == null : this.getCheckoutTime().equals(other.getCheckoutTime()))
            && (this.getCheckoutUpload() == null ? other.getCheckoutUpload() == null : this.getCheckoutUpload().equals(other.getCheckoutUpload()))
            && (this.getParamExt() == null ? other.getParamExt() == null : this.getParamExt().equals(other.getParamExt()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getCardType() == null) ? 0 : getCardType().hashCode());
        result = prime * result + ((getCredentialNo() == null) ? 0 : getCredentialNo().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getNation() == null) ? 0 : getNation().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getCredentialValidStart() == null) ? 0 : getCredentialValidStart().hashCode());
        result = prime * result + ((getCredentialValidEnd() == null) ? 0 : getCredentialValidEnd().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getHotelCode() == null) ? 0 : getHotelCode().hashCode());
        result = prime * result + ((getRoomNo() == null) ? 0 : getRoomNo().hashCode());
        result = prime * result + ((getCredentialImage() == null) ? 0 : getCredentialImage().hashCode());
        result = prime * result + ((getFaceImage() == null) ? 0 : getFaceImage().hashCode());
        result = prime * result + ((getVerifyResult() == null) ? 0 : getVerifyResult().hashCode());
        result = prime * result + ((getVerifyScore() == null) ? 0 : getVerifyScore().hashCode());
        result = prime * result + ((getCheckinTime() == null) ? 0 : getCheckinTime().hashCode());
        result = prime * result + ((getCheckinUpload() == null) ? 0 : getCheckinUpload().hashCode());
        result = prime * result + ((getCheckoutTime() == null) ? 0 : getCheckoutTime().hashCode());
        result = prime * result + ((getCheckoutUpload() == null) ? 0 : getCheckoutUpload().hashCode());
        result = prime * result + ((getParamExt() == null) ? 0 : getParamExt().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        return result;
    }
}