package cn.xpms.third.security.dao.generator.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class PublicSecurityConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.id
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.hotel_code
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private String hotelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.username
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.password
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.on_or_off
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private String onOrOff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.norify_url
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private String norifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.valid
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.create_user
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.create_time
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.modify_user
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.modify_time
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_config.memo
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", hotelCode=").append(hotelCode);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", onOrOff=").append(onOrOff);
        sb.append(", norifyUrl=").append(norifyUrl);
        sb.append(", valid=").append(valid);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", memo=").append(memo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PublicSecurityConfig other = (PublicSecurityConfig) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getHotelCode() == null ? other.getHotelCode() == null : this.getHotelCode().equals(other.getHotelCode()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getOnOrOff() == null ? other.getOnOrOff() == null : this.getOnOrOff().equals(other.getOnOrOff()))
            && (this.getNorifyUrl() == null ? other.getNorifyUrl() == null : this.getNorifyUrl().equals(other.getNorifyUrl()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getHotelCode() == null) ? 0 : getHotelCode().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getOnOrOff() == null) ? 0 : getOnOrOff().hashCode());
        result = prime * result + ((getNorifyUrl() == null) ? 0 : getNorifyUrl().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        return result;
    }
}