package cn.xpms.third.security.dao.generator.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class PublicSecurityUploadRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.id
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.info_id
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    private Integer infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.upload_type
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    private String uploadType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.upload_result
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    private String uploadResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.upload_times
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    private Integer uploadTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.valid
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.create_user
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.create_time
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.modify_user
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.modify_time
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_security_upload_record.memo
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", infoId=").append(infoId);
        sb.append(", uploadType=").append(uploadType);
        sb.append(", uploadResult=").append(uploadResult);
        sb.append(", uploadTimes=").append(uploadTimes);
        sb.append(", valid=").append(valid);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", memo=").append(memo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PublicSecurityUploadRecord other = (PublicSecurityUploadRecord) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getInfoId() == null ? other.getInfoId() == null : this.getInfoId().equals(other.getInfoId()))
            && (this.getUploadType() == null ? other.getUploadType() == null : this.getUploadType().equals(other.getUploadType()))
            && (this.getUploadResult() == null ? other.getUploadResult() == null : this.getUploadResult().equals(other.getUploadResult()))
            && (this.getUploadTimes() == null ? other.getUploadTimes() == null : this.getUploadTimes().equals(other.getUploadTimes()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getInfoId() == null) ? 0 : getInfoId().hashCode());
        result = prime * result + ((getUploadType() == null) ? 0 : getUploadType().hashCode());
        result = prime * result + ((getUploadResult() == null) ? 0 : getUploadResult().hashCode());
        result = prime * result + ((getUploadTimes() == null) ? 0 : getUploadTimes().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        return result;
    }
}