package cn.xpms.member.coupon.dao.generator.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class MemberCouponInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.id
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.coupon_type
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private String couponType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.code
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.title
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.description
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.total_count
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private Integer totalCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.surplus_count
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private Integer surplusCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.date_type
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private String dateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.date_begin
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date dateBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.date_end
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date dateEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.date_num
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private Integer dateNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.date_begin_num
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private Integer dateBeginNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.least_cost
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private BigDecimal leastCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.reduce_cost
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private BigDecimal reduceCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.discount
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.notify_url
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private String notifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.status
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.valid
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.create_user
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.create_time
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.modify_user
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.modify_time
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_coupon_info.memo
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", couponType=").append(couponType);
        sb.append(", code=").append(code);
        sb.append(", title=").append(title);
        sb.append(", description=").append(description);
        sb.append(", totalCount=").append(totalCount);
        sb.append(", surplusCount=").append(surplusCount);
        sb.append(", dateType=").append(dateType);
        sb.append(", dateBegin=").append(dateBegin);
        sb.append(", dateEnd=").append(dateEnd);
        sb.append(", dateNum=").append(dateNum);
        sb.append(", dateBeginNum=").append(dateBeginNum);
        sb.append(", leastCost=").append(leastCost);
        sb.append(", reduceCost=").append(reduceCost);
        sb.append(", discount=").append(discount);
        sb.append(", notifyUrl=").append(notifyUrl);
        sb.append(", status=").append(status);
        sb.append(", valid=").append(valid);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", memo=").append(memo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MemberCouponInfo other = (MemberCouponInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCouponType() == null ? other.getCouponType() == null : this.getCouponType().equals(other.getCouponType()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getTotalCount() == null ? other.getTotalCount() == null : this.getTotalCount().equals(other.getTotalCount()))
            && (this.getSurplusCount() == null ? other.getSurplusCount() == null : this.getSurplusCount().equals(other.getSurplusCount()))
            && (this.getDateType() == null ? other.getDateType() == null : this.getDateType().equals(other.getDateType()))
            && (this.getDateBegin() == null ? other.getDateBegin() == null : this.getDateBegin().equals(other.getDateBegin()))
            && (this.getDateEnd() == null ? other.getDateEnd() == null : this.getDateEnd().equals(other.getDateEnd()))
            && (this.getDateNum() == null ? other.getDateNum() == null : this.getDateNum().equals(other.getDateNum()))
            && (this.getDateBeginNum() == null ? other.getDateBeginNum() == null : this.getDateBeginNum().equals(other.getDateBeginNum()))
            && (this.getLeastCost() == null ? other.getLeastCost() == null : this.getLeastCost().equals(other.getLeastCost()))
            && (this.getReduceCost() == null ? other.getReduceCost() == null : this.getReduceCost().equals(other.getReduceCost()))
            && (this.getDiscount() == null ? other.getDiscount() == null : this.getDiscount().equals(other.getDiscount()))
            && (this.getNotifyUrl() == null ? other.getNotifyUrl() == null : this.getNotifyUrl().equals(other.getNotifyUrl()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCouponType() == null) ? 0 : getCouponType().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getTotalCount() == null) ? 0 : getTotalCount().hashCode());
        result = prime * result + ((getSurplusCount() == null) ? 0 : getSurplusCount().hashCode());
        result = prime * result + ((getDateType() == null) ? 0 : getDateType().hashCode());
        result = prime * result + ((getDateBegin() == null) ? 0 : getDateBegin().hashCode());
        result = prime * result + ((getDateEnd() == null) ? 0 : getDateEnd().hashCode());
        result = prime * result + ((getDateNum() == null) ? 0 : getDateNum().hashCode());
        result = prime * result + ((getDateBeginNum() == null) ? 0 : getDateBeginNum().hashCode());
        result = prime * result + ((getLeastCost() == null) ? 0 : getLeastCost().hashCode());
        result = prime * result + ((getReduceCost() == null) ? 0 : getReduceCost().hashCode());
        result = prime * result + ((getDiscount() == null) ? 0 : getDiscount().hashCode());
        result = prime * result + ((getNotifyUrl() == null) ? 0 : getNotifyUrl().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        return result;
    }
}