package cn.xpms.member.coupon.dao.generator.repository;

import cn.xpms.member.coupon.dao.generator.entity.MemberCouponInfo;
import cn.xpms.member.coupon.dao.generator.entity.MemberCouponInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MemberCouponInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    long countByExample(MemberCouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    int deleteByExample(MemberCouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    int insert(MemberCouponInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    int insertSelective(MemberCouponInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    List<MemberCouponInfo> selectByExampleWithRowbounds(MemberCouponInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    List<MemberCouponInfo> selectByExample(MemberCouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    MemberCouponInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") MemberCouponInfo record, @Param("example") MemberCouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    int updateByExample(@Param("record") MemberCouponInfo record, @Param("example") MemberCouponInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    int updateByPrimaryKeySelective(MemberCouponInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_coupon_info
     *
     * @mbg.generated Tue Nov 03 15:59:00 CST 2020
     */
    int updateByPrimaryKey(MemberCouponInfo record);
}