package cn.xpms.member.coupon.dao.generator.repository;

import cn.xpms.member.coupon.dao.generator.entity.MemberDict;
import cn.xpms.member.coupon.dao.generator.entity.MemberDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MemberDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    long countByExample(MemberDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    int deleteByExample(MemberDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    int insert(MemberDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    int insertSelective(MemberDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    List<MemberDict> selectByExampleWithRowbounds(MemberDictExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    List<MemberDict> selectByExample(MemberDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    MemberDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") MemberDict record, @Param("example") MemberDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    int updateByExample(@Param("record") MemberDict record, @Param("example") MemberDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    int updateByPrimaryKeySelective(MemberDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_dict
     *
     * @mbg.generated Wed Nov 18 10:43:53 CST 2020
     */
    int updateByPrimaryKey(MemberDict record);
}