server:
  port: 8093

spring:
  application:
    name: sso
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.129.228.217:3306/xpms_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: zrz560215@
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  resources:
    static-locations: classpath:/templates/
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    timeout: 30000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL

eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone: http://www.xpms.cn:5060/eureka/eureka

mybatis:
  mapper-locations: classpath*:/cn/xpms/**/**/*.xml

#打印sql时的语句
logging:
  level:
    cn:
      xpms: debug

#系统配置
system:
  swagger:
    path-mapping: /
    base-package: cn.xpms.sso
    title: 单点登录平台
    description: sso单点登录平台
    version: 1.0
    licene:
      title: 单点登录平台接口规范
      url: http://www.baidu.com
  sso:
    domain: http://localhost:8093
  login-filter: true
  logout-filter: true