package cn.xpms.paas.api.dao.generator.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class PaasDeviceInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.id
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.device_id
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.product_id
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.product_name
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.category
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.category_code
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String categoryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.name
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.active_time
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date activeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.gmt_time
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date gmtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.online
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String online;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.software_version
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String softwareVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.product_module
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String productModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.position
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.project_id
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.room_id
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.scene
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private Integer scene;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.condition
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private Integer condition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.action
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private Integer action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.valid
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.create_user
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.create_time
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.modify_user
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.modify_time
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_device_info.memo
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", category=").append(category);
        sb.append(", categoryCode=").append(categoryCode);
        sb.append(", name=").append(name);
        sb.append(", activeTime=").append(activeTime);
        sb.append(", gmtTime=").append(gmtTime);
        sb.append(", online=").append(online);
        sb.append(", softwareVersion=").append(softwareVersion);
        sb.append(", productModule=").append(productModule);
        sb.append(", position=").append(position);
        sb.append(", projectId=").append(projectId);
        sb.append(", roomId=").append(roomId);
        sb.append(", scene=").append(scene);
        sb.append(", condition=").append(condition);
        sb.append(", action=").append(action);
        sb.append(", valid=").append(valid);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", memo=").append(memo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PaasDeviceInfo other = (PaasDeviceInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDeviceId() == null ? other.getDeviceId() == null : this.getDeviceId().equals(other.getDeviceId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()))
            && (this.getCategoryCode() == null ? other.getCategoryCode() == null : this.getCategoryCode().equals(other.getCategoryCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getActiveTime() == null ? other.getActiveTime() == null : this.getActiveTime().equals(other.getActiveTime()))
            && (this.getGmtTime() == null ? other.getGmtTime() == null : this.getGmtTime().equals(other.getGmtTime()))
            && (this.getOnline() == null ? other.getOnline() == null : this.getOnline().equals(other.getOnline()))
            && (this.getSoftwareVersion() == null ? other.getSoftwareVersion() == null : this.getSoftwareVersion().equals(other.getSoftwareVersion()))
            && (this.getProductModule() == null ? other.getProductModule() == null : this.getProductModule().equals(other.getProductModule()))
            && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()))
            && (this.getProjectId() == null ? other.getProjectId() == null : this.getProjectId().equals(other.getProjectId()))
            && (this.getRoomId() == null ? other.getRoomId() == null : this.getRoomId().equals(other.getRoomId()))
            && (this.getScene() == null ? other.getScene() == null : this.getScene().equals(other.getScene()))
            && (this.getCondition() == null ? other.getCondition() == null : this.getCondition().equals(other.getCondition()))
            && (this.getAction() == null ? other.getAction() == null : this.getAction().equals(other.getAction()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDeviceId() == null) ? 0 : getDeviceId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        result = prime * result + ((getCategoryCode() == null) ? 0 : getCategoryCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getActiveTime() == null) ? 0 : getActiveTime().hashCode());
        result = prime * result + ((getGmtTime() == null) ? 0 : getGmtTime().hashCode());
        result = prime * result + ((getOnline() == null) ? 0 : getOnline().hashCode());
        result = prime * result + ((getSoftwareVersion() == null) ? 0 : getSoftwareVersion().hashCode());
        result = prime * result + ((getProductModule() == null) ? 0 : getProductModule().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        result = prime * result + ((getRoomId() == null) ? 0 : getRoomId().hashCode());
        result = prime * result + ((getScene() == null) ? 0 : getScene().hashCode());
        result = prime * result + ((getCondition() == null) ? 0 : getCondition().hashCode());
        result = prime * result + ((getAction() == null) ? 0 : getAction().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        return result;
    }
}