package cn.xpms.paas.api.dao.generator.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class PaasConstructionTemplateInfraredDevice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.id
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.position_id
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private String positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.category_id
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.brand_id
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private String brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.remote
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private String remote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.area_id
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.custom_device_name
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private String customDeviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.operator_id
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private String operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.valid
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.create_user
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.create_time
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.modify_user
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.modify_time
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_construction_template_infrared_device.memo
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", positionId=").append(positionId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", brandId=").append(brandId);
        sb.append(", remote=").append(remote);
        sb.append(", areaId=").append(areaId);
        sb.append(", customDeviceName=").append(customDeviceName);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", valid=").append(valid);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", memo=").append(memo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PaasConstructionTemplateInfraredDevice other = (PaasConstructionTemplateInfraredDevice) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPositionId() == null ? other.getPositionId() == null : this.getPositionId().equals(other.getPositionId()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getBrandId() == null ? other.getBrandId() == null : this.getBrandId().equals(other.getBrandId()))
            && (this.getRemote() == null ? other.getRemote() == null : this.getRemote().equals(other.getRemote()))
            && (this.getAreaId() == null ? other.getAreaId() == null : this.getAreaId().equals(other.getAreaId()))
            && (this.getCustomDeviceName() == null ? other.getCustomDeviceName() == null : this.getCustomDeviceName().equals(other.getCustomDeviceName()))
            && (this.getOperatorId() == null ? other.getOperatorId() == null : this.getOperatorId().equals(other.getOperatorId()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPositionId() == null) ? 0 : getPositionId().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getBrandId() == null) ? 0 : getBrandId().hashCode());
        result = prime * result + ((getRemote() == null) ? 0 : getRemote().hashCode());
        result = prime * result + ((getAreaId() == null) ? 0 : getAreaId().hashCode());
        result = prime * result + ((getCustomDeviceName() == null) ? 0 : getCustomDeviceName().hashCode());
        result = prime * result + ((getOperatorId() == null) ? 0 : getOperatorId().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        return result;
    }
}