package cn.xpms.paas.api.dao.generator.entity;

import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class PaasContractorAuthorizationKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_contractor_authorization.id
     *
     * @mbg.generated Fri Nov 27 10:12:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_contractor_authorization.authorization_id
     *
     * @mbg.generated Fri Nov 27 10:12:41 CST 2020
     */
    private String authorizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paas_contractor_authorization
     *
     * @mbg.generated Fri Nov 27 10:12:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_contractor_authorization
     *
     * @mbg.generated Fri Nov 27 10:12:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", authorizationId=").append(authorizationId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_contractor_authorization
     *
     * @mbg.generated Fri Nov 27 10:12:41 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PaasContractorAuthorizationKey other = (PaasContractorAuthorizationKey) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAuthorizationId() == null ? other.getAuthorizationId() == null : this.getAuthorizationId().equals(other.getAuthorizationId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_contractor_authorization
     *
     * @mbg.generated Fri Nov 27 10:12:41 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAuthorizationId() == null) ? 0 : getAuthorizationId().hashCode());
        return result;
    }
}