package cn.xpms.paas.api.dao.generator.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class PaasPlusarMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.id
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.data
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.biz_code
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private String bizCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.biz_name
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private String bizName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.event_type
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private String eventType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.event_name
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private String eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.sign
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.encrypt_type
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private String encryptType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.t
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private String t;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.v
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private String v;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_plusar_message.generate_time
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date generateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paas_plusar_message
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_plusar_message
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", data=").append(data);
        sb.append(", bizCode=").append(bizCode);
        sb.append(", bizName=").append(bizName);
        sb.append(", eventType=").append(eventType);
        sb.append(", eventName=").append(eventName);
        sb.append(", sign=").append(sign);
        sb.append(", encryptType=").append(encryptType);
        sb.append(", t=").append(t);
        sb.append(", v=").append(v);
        sb.append(", generateTime=").append(generateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_plusar_message
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PaasPlusarMessage other = (PaasPlusarMessage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getData() == null ? other.getData() == null : this.getData().equals(other.getData()))
            && (this.getBizCode() == null ? other.getBizCode() == null : this.getBizCode().equals(other.getBizCode()))
            && (this.getBizName() == null ? other.getBizName() == null : this.getBizName().equals(other.getBizName()))
            && (this.getEventType() == null ? other.getEventType() == null : this.getEventType().equals(other.getEventType()))
            && (this.getEventName() == null ? other.getEventName() == null : this.getEventName().equals(other.getEventName()))
            && (this.getSign() == null ? other.getSign() == null : this.getSign().equals(other.getSign()))
            && (this.getEncryptType() == null ? other.getEncryptType() == null : this.getEncryptType().equals(other.getEncryptType()))
            && (this.getT() == null ? other.getT() == null : this.getT().equals(other.getT()))
            && (this.getV() == null ? other.getV() == null : this.getV().equals(other.getV()))
            && (this.getGenerateTime() == null ? other.getGenerateTime() == null : this.getGenerateTime().equals(other.getGenerateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_plusar_message
     *
     * @mbg.generated Thu Dec 17 14:35:13 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getData() == null) ? 0 : getData().hashCode());
        result = prime * result + ((getBizCode() == null) ? 0 : getBizCode().hashCode());
        result = prime * result + ((getBizName() == null) ? 0 : getBizName().hashCode());
        result = prime * result + ((getEventType() == null) ? 0 : getEventType().hashCode());
        result = prime * result + ((getEventName() == null) ? 0 : getEventName().hashCode());
        result = prime * result + ((getSign() == null) ? 0 : getSign().hashCode());
        result = prime * result + ((getEncryptType() == null) ? 0 : getEncryptType().hashCode());
        result = prime * result + ((getT() == null) ? 0 : getT().hashCode());
        result = prime * result + ((getV() == null) ? 0 : getV().hashCode());
        result = prime * result + ((getGenerateTime() == null) ? 0 : getGenerateTime().hashCode());
        return result;
    }
}