package cn.xpms.paas.api.dao.generator.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class PaasCustomAutomationCondition implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.id
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.automation_id
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private Integer automationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.device_id
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.device_status_name
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private String deviceStatusName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.device_status_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private String deviceStatusType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.device_status_value
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private String deviceStatusValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.device_status_count
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private Integer deviceStatusCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.desc
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.order_num
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.valid
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private Integer valid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.create_user
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.create_time
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.modify_user
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.modify_time
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paas_custom_automation_condition.memo
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", automationId=").append(automationId);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", deviceStatusName=").append(deviceStatusName);
        sb.append(", deviceStatusType=").append(deviceStatusType);
        sb.append(", deviceStatusValue=").append(deviceStatusValue);
        sb.append(", deviceStatusCount=").append(deviceStatusCount);
        sb.append(", desc=").append(desc);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", valid=").append(valid);
        sb.append(", createUser=").append(createUser);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", memo=").append(memo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PaasCustomAutomationCondition other = (PaasCustomAutomationCondition) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAutomationId() == null ? other.getAutomationId() == null : this.getAutomationId().equals(other.getAutomationId()))
            && (this.getDeviceId() == null ? other.getDeviceId() == null : this.getDeviceId().equals(other.getDeviceId()))
            && (this.getDeviceStatusName() == null ? other.getDeviceStatusName() == null : this.getDeviceStatusName().equals(other.getDeviceStatusName()))
            && (this.getDeviceStatusType() == null ? other.getDeviceStatusType() == null : this.getDeviceStatusType().equals(other.getDeviceStatusType()))
            && (this.getDeviceStatusValue() == null ? other.getDeviceStatusValue() == null : this.getDeviceStatusValue().equals(other.getDeviceStatusValue()))
            && (this.getDeviceStatusCount() == null ? other.getDeviceStatusCount() == null : this.getDeviceStatusCount().equals(other.getDeviceStatusCount()))
            && (this.getDesc() == null ? other.getDesc() == null : this.getDesc().equals(other.getDesc()))
            && (this.getOrderNum() == null ? other.getOrderNum() == null : this.getOrderNum().equals(other.getOrderNum()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyUser() == null ? other.getModifyUser() == null : this.getModifyUser().equals(other.getModifyUser()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAutomationId() == null) ? 0 : getAutomationId().hashCode());
        result = prime * result + ((getDeviceId() == null) ? 0 : getDeviceId().hashCode());
        result = prime * result + ((getDeviceStatusName() == null) ? 0 : getDeviceStatusName().hashCode());
        result = prime * result + ((getDeviceStatusType() == null) ? 0 : getDeviceStatusType().hashCode());
        result = prime * result + ((getDeviceStatusValue() == null) ? 0 : getDeviceStatusValue().hashCode());
        result = prime * result + ((getDeviceStatusCount() == null) ? 0 : getDeviceStatusCount().hashCode());
        result = prime * result + ((getDesc() == null) ? 0 : getDesc().hashCode());
        result = prime * result + ((getOrderNum() == null) ? 0 : getOrderNum().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyUser() == null) ? 0 : getModifyUser().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        return result;
    }
}