package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplatePreconditionDisplay;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplatePreconditionDisplayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationTemplatePreconditionDisplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    long countByExample(PaasAutomationTemplatePreconditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int deleteByExample(PaasAutomationTemplatePreconditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int insert(PaasAutomationTemplatePreconditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int insertSelective(PaasAutomationTemplatePreconditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    List<PaasAutomationTemplatePreconditionDisplay> selectByExampleWithRowbounds(PaasAutomationTemplatePreconditionDisplayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    List<PaasAutomationTemplatePreconditionDisplay> selectByExample(PaasAutomationTemplatePreconditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    PaasAutomationTemplatePreconditionDisplay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasAutomationTemplatePreconditionDisplay record, @Param("example") PaasAutomationTemplatePreconditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByExample(@Param("record") PaasAutomationTemplatePreconditionDisplay record, @Param("example") PaasAutomationTemplatePreconditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByPrimaryKeySelective(PaasAutomationTemplatePreconditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition_display
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByPrimaryKey(PaasAutomationTemplatePreconditionDisplay record);
}