package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplate;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    long countByExample(PaasAutomationTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int deleteByExample(PaasAutomationTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int insert(PaasAutomationTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int insertSelective(PaasAutomationTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    List<PaasAutomationTemplate> selectByExampleWithRowbounds(PaasAutomationTemplateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    List<PaasAutomationTemplate> selectByExample(PaasAutomationTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    PaasAutomationTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasAutomationTemplate record, @Param("example") PaasAutomationTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByExample(@Param("record") PaasAutomationTemplate record, @Param("example") PaasAutomationTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByPrimaryKeySelective(PaasAutomationTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByPrimaryKey(PaasAutomationTemplate record);
}