package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasDeviceInfoStatus;
import cn.xpms.paas.api.dao.generator.entity.PaasDeviceInfoStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasDeviceInfoStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    long countByExample(PaasDeviceInfoStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int deleteByExample(PaasDeviceInfoStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int insert(PaasDeviceInfoStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int insertSelective(PaasDeviceInfoStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    List<PaasDeviceInfoStatus> selectByExampleWithRowbounds(PaasDeviceInfoStatusExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    List<PaasDeviceInfoStatus> selectByExample(PaasDeviceInfoStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    PaasDeviceInfoStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasDeviceInfoStatus record, @Param("example") PaasDeviceInfoStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int updateByExample(@Param("record") PaasDeviceInfoStatus record, @Param("example") PaasDeviceInfoStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int updateByPrimaryKeySelective(PaasDeviceInfoStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_status
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int updateByPrimaryKey(PaasDeviceInfoStatus record);
}