package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasWorkerInfo;
import cn.xpms.paas.api.dao.generator.entity.PaasWorkerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasWorkerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasWorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasWorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasWorkerInfo> selectByExampleWithRowbounds(PaasWorkerInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasWorkerInfo> selectByExample(PaasWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasWorkerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasWorkerInfo record, @Param("example") PaasWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasWorkerInfo record, @Param("example") PaasWorkerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasWorkerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_worker_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasWorkerInfo record);
}