package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasConstructionTask;
import cn.xpms.paas.api.dao.generator.entity.PaasConstructionTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasConstructionTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    long countByExample(PaasConstructionTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    int deleteByExample(PaasConstructionTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    int insert(PaasConstructionTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    int insertSelective(PaasConstructionTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    List<PaasConstructionTask> selectByExampleWithRowbounds(PaasConstructionTaskExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    List<PaasConstructionTask> selectByExample(PaasConstructionTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    PaasConstructionTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasConstructionTask record, @Param("example") PaasConstructionTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    int updateByExample(@Param("record") PaasConstructionTask record, @Param("example") PaasConstructionTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    int updateByPrimaryKeySelective(PaasConstructionTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task
     *
     * @mbg.generated Mon Dec 07 10:33:14 CST 2020
     */
    int updateByPrimaryKey(PaasConstructionTask record);
}