package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasSceneTemplateActionExecutor;
import cn.xpms.paas.api.dao.generator.entity.PaasSceneTemplateActionExecutorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasSceneTemplateActionExecutorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    long countByExample(PaasSceneTemplateActionExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    int deleteByExample(PaasSceneTemplateActionExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    int insert(PaasSceneTemplateActionExecutor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    int insertSelective(PaasSceneTemplateActionExecutor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    List<PaasSceneTemplateActionExecutor> selectByExampleWithRowbounds(PaasSceneTemplateActionExecutorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    List<PaasSceneTemplateActionExecutor> selectByExample(PaasSceneTemplateActionExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    PaasSceneTemplateActionExecutor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasSceneTemplateActionExecutor record, @Param("example") PaasSceneTemplateActionExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    int updateByExample(@Param("record") PaasSceneTemplateActionExecutor record, @Param("example") PaasSceneTemplateActionExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    int updateByPrimaryKeySelective(PaasSceneTemplateActionExecutor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:14:20 CST 2021
     */
    int updateByPrimaryKey(PaasSceneTemplateActionExecutor record);
}