package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationPrecondition;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationPreconditionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationPreconditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    long countByExample(PaasAutomationPreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int deleteByExample(PaasAutomationPreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int insert(PaasAutomationPrecondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int insertSelective(PaasAutomationPrecondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    List<PaasAutomationPrecondition> selectByExampleWithRowbounds(PaasAutomationPreconditionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    List<PaasAutomationPrecondition> selectByExample(PaasAutomationPreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    PaasAutomationPrecondition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasAutomationPrecondition record, @Param("example") PaasAutomationPreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int updateByExample(@Param("record") PaasAutomationPrecondition record, @Param("example") PaasAutomationPreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int updateByPrimaryKeySelective(PaasAutomationPrecondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int updateByPrimaryKey(PaasAutomationPrecondition record);
}