package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasConfig;
import cn.xpms.paas.api.dao.generator.entity.PaasConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasConfig> selectByExampleWithRowbounds(PaasConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasConfig> selectByExample(PaasConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasConfig record, @Param("example") PaasConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasConfig record, @Param("example") PaasConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_config
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasConfig record);
}