package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationTemplateCondition;
import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationTemplateConditionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasCustomAutomationTemplateConditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    long countByExample(PaasCustomAutomationTemplateConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    int deleteByExample(PaasCustomAutomationTemplateConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    int insert(PaasCustomAutomationTemplateCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    int insertSelective(PaasCustomAutomationTemplateCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    List<PaasCustomAutomationTemplateCondition> selectByExampleWithRowbounds(PaasCustomAutomationTemplateConditionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    List<PaasCustomAutomationTemplateCondition> selectByExample(PaasCustomAutomationTemplateConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    PaasCustomAutomationTemplateCondition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasCustomAutomationTemplateCondition record, @Param("example") PaasCustomAutomationTemplateConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    int updateByExample(@Param("record") PaasCustomAutomationTemplateCondition record, @Param("example") PaasCustomAutomationTemplateConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    int updateByPrimaryKeySelective(PaasCustomAutomationTemplateCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_condition
     *
     * @mbg.generated Tue Jan 12 17:00:01 CST 2021
     */
    int updateByPrimaryKey(PaasCustomAutomationTemplateCondition record);
}