package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasRoomGuest;
import cn.xpms.paas.api.dao.generator.entity.PaasRoomGuestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasRoomGuestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    long countByExample(PaasRoomGuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    int deleteByExample(PaasRoomGuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    int insert(PaasRoomGuest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    int insertSelective(PaasRoomGuest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    List<PaasRoomGuest> selectByExampleWithRowbounds(PaasRoomGuestExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    List<PaasRoomGuest> selectByExample(PaasRoomGuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    PaasRoomGuest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasRoomGuest record, @Param("example") PaasRoomGuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    int updateByExample(@Param("record") PaasRoomGuest record, @Param("example") PaasRoomGuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    int updateByPrimaryKeySelective(PaasRoomGuest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_guest
     *
     * @mbg.generated Thu Jan 21 08:38:33 CST 2021
     */
    int updateByPrimaryKey(PaasRoomGuest record);
}