package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasMaintenanceTask;
import cn.xpms.paas.api.dao.generator.entity.PaasMaintenanceTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasMaintenanceTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasMaintenanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasMaintenanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasMaintenanceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasMaintenanceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasMaintenanceTask> selectByExampleWithRowbounds(PaasMaintenanceTaskExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasMaintenanceTask> selectByExample(PaasMaintenanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasMaintenanceTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasMaintenanceTask record, @Param("example") PaasMaintenanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasMaintenanceTask record, @Param("example") PaasMaintenanceTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasMaintenanceTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasMaintenanceTask record);
}