package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasDeviceInfoLatestStatus;
import cn.xpms.paas.api.dao.generator.entity.PaasDeviceInfoLatestStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasDeviceInfoLatestStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    long countByExample(PaasDeviceInfoLatestStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    int deleteByExample(PaasDeviceInfoLatestStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    int insert(PaasDeviceInfoLatestStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    int insertSelective(PaasDeviceInfoLatestStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    List<PaasDeviceInfoLatestStatus> selectByExampleWithRowbounds(PaasDeviceInfoLatestStatusExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    List<PaasDeviceInfoLatestStatus> selectByExample(PaasDeviceInfoLatestStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    PaasDeviceInfoLatestStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasDeviceInfoLatestStatus record, @Param("example") PaasDeviceInfoLatestStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    int updateByExample(@Param("record") PaasDeviceInfoLatestStatus record, @Param("example") PaasDeviceInfoLatestStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    int updateByPrimaryKeySelective(PaasDeviceInfoLatestStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_latest_status
     *
     * @mbg.generated Tue Dec 08 09:08:00 CST 2020
     */
    int updateByPrimaryKey(PaasDeviceInfoLatestStatus record);
}