package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasConstructionTaskRoom;
import cn.xpms.paas.api.dao.generator.entity.PaasConstructionTaskRoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasConstructionTaskRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasConstructionTaskRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasConstructionTaskRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasConstructionTaskRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasConstructionTaskRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasConstructionTaskRoom> selectByExampleWithRowbounds(PaasConstructionTaskRoomExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasConstructionTaskRoom> selectByExample(PaasConstructionTaskRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasConstructionTaskRoom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasConstructionTaskRoom record, @Param("example") PaasConstructionTaskRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasConstructionTaskRoom record, @Param("example") PaasConstructionTaskRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasConstructionTaskRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasConstructionTaskRoom record);
}