package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasDict;
import cn.xpms.paas.api.dao.generator.entity.PaasDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasDict> selectByExampleWithRowbounds(PaasDictExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasDict> selectByExample(PaasDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasDict record, @Param("example") PaasDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasDict record, @Param("example") PaasDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_dict
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasDict record);
}