package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationTemplateScene;
import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationTemplateSceneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasCustomAutomationTemplateSceneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    long countByExample(PaasCustomAutomationTemplateSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int deleteByExample(PaasCustomAutomationTemplateSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int insert(PaasCustomAutomationTemplateScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int insertSelective(PaasCustomAutomationTemplateScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    List<PaasCustomAutomationTemplateScene> selectByExampleWithRowbounds(PaasCustomAutomationTemplateSceneExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    List<PaasCustomAutomationTemplateScene> selectByExample(PaasCustomAutomationTemplateSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    PaasCustomAutomationTemplateScene selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasCustomAutomationTemplateScene record, @Param("example") PaasCustomAutomationTemplateSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByExample(@Param("record") PaasCustomAutomationTemplateScene record, @Param("example") PaasCustomAutomationTemplateSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByPrimaryKeySelective(PaasCustomAutomationTemplateScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByPrimaryKey(PaasCustomAutomationTemplateScene record);
}