package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplateAction;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplateActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationTemplateActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    long countByExample(PaasAutomationTemplateActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int deleteByExample(PaasAutomationTemplateActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int insert(PaasAutomationTemplateAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int insertSelective(PaasAutomationTemplateAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    List<PaasAutomationTemplateAction> selectByExampleWithRowbounds(PaasAutomationTemplateActionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    List<PaasAutomationTemplateAction> selectByExample(PaasAutomationTemplateActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    PaasAutomationTemplateAction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasAutomationTemplateAction record, @Param("example") PaasAutomationTemplateActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByExample(@Param("record") PaasAutomationTemplateAction record, @Param("example") PaasAutomationTemplateActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByPrimaryKeySelective(PaasAutomationTemplateAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByPrimaryKey(PaasAutomationTemplateAction record);
}