package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasApiCallRecord;
import cn.xpms.paas.api.dao.generator.entity.PaasApiCallRecordExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasApiCallRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    long countByExample(PaasApiCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    int deleteByExample(PaasApiCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    int insert(PaasApiCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    int insertSelective(PaasApiCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    List<PaasApiCallRecord> selectByExampleWithBLOBsWithRowbounds(PaasApiCallRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    List<PaasApiCallRecord> selectByExampleWithBLOBs(PaasApiCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    List<PaasApiCallRecord> selectByExampleWithRowbounds(PaasApiCallRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    List<PaasApiCallRecord> selectByExample(PaasApiCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    PaasApiCallRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasApiCallRecord record, @Param("example") PaasApiCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") PaasApiCallRecord record, @Param("example") PaasApiCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    int updateByExample(@Param("record") PaasApiCallRecord record, @Param("example") PaasApiCallRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    int updateByPrimaryKeySelective(PaasApiCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(PaasApiCallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_call_record
     *
     * @mbg.generated Wed Dec 02 11:15:02 CST 2020
     */
    int updateByPrimaryKey(PaasApiCallRecord record);
}