package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasDeviceInfo;
import cn.xpms.paas.api.dao.generator.entity.PaasDeviceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasDeviceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    long countByExample(PaasDeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    int deleteByExample(PaasDeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    int insert(PaasDeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    int insertSelective(PaasDeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    List<PaasDeviceInfo> selectByExampleWithRowbounds(PaasDeviceInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    List<PaasDeviceInfo> selectByExample(PaasDeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    PaasDeviceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasDeviceInfo record, @Param("example") PaasDeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    int updateByExample(@Param("record") PaasDeviceInfo record, @Param("example") PaasDeviceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    int updateByPrimaryKeySelective(PaasDeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info
     *
     * @mbg.generated Wed Dec 16 15:29:51 CST 2020
     */
    int updateByPrimaryKey(PaasDeviceInfo record);
}