package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasSceneTemplateScene;
import cn.xpms.paas.api.dao.generator.entity.PaasSceneTemplateSceneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasSceneTemplateSceneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    long countByExample(PaasSceneTemplateSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    int deleteByExample(PaasSceneTemplateSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    int insert(PaasSceneTemplateScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    int insertSelective(PaasSceneTemplateScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    List<PaasSceneTemplateScene> selectByExampleWithRowbounds(PaasSceneTemplateSceneExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    List<PaasSceneTemplateScene> selectByExample(PaasSceneTemplateSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    PaasSceneTemplateScene selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasSceneTemplateScene record, @Param("example") PaasSceneTemplateSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    int updateByExample(@Param("record") PaasSceneTemplateScene record, @Param("example") PaasSceneTemplateSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    int updateByPrimaryKeySelective(PaasSceneTemplateScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_scene
     *
     * @mbg.generated Tue Dec 29 15:20:22 CST 2020
     */
    int updateByPrimaryKey(PaasSceneTemplateScene record);
}