package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationAction;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    long countByExample(PaasAutomationActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int deleteByExample(PaasAutomationActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int insert(PaasAutomationAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int insertSelective(PaasAutomationAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    List<PaasAutomationAction> selectByExampleWithRowbounds(PaasAutomationActionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    List<PaasAutomationAction> selectByExample(PaasAutomationActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    PaasAutomationAction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasAutomationAction record, @Param("example") PaasAutomationActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int updateByExample(@Param("record") PaasAutomationAction record, @Param("example") PaasAutomationActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int updateByPrimaryKeySelective(PaasAutomationAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action
     *
     * @mbg.generated Thu Dec 17 10:57:49 CST 2020
     */
    int updateByPrimaryKey(PaasAutomationAction record);
}