package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasSpaceInfo;
import cn.xpms.paas.api.dao.generator.entity.PaasSpaceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasSpaceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasSpaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasSpaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasSpaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasSpaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasSpaceInfo> selectByExampleWithRowbounds(PaasSpaceInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasSpaceInfo> selectByExample(PaasSpaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasSpaceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasSpaceInfo record, @Param("example") PaasSpaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasSpaceInfo record, @Param("example") PaasSpaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasSpaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_space_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasSpaceInfo record);
}