package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasSceneActionExecutorProperty;
import cn.xpms.paas.api.dao.generator.entity.PaasSceneActionExecutorPropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasSceneActionExecutorPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    long countByExample(PaasSceneActionExecutorPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int deleteByExample(PaasSceneActionExecutorPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int insert(PaasSceneActionExecutorProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int insertSelective(PaasSceneActionExecutorProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    List<PaasSceneActionExecutorProperty> selectByExampleWithRowbounds(PaasSceneActionExecutorPropertyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    List<PaasSceneActionExecutorProperty> selectByExample(PaasSceneActionExecutorPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    PaasSceneActionExecutorProperty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasSceneActionExecutorProperty record, @Param("example") PaasSceneActionExecutorPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int updateByExample(@Param("record") PaasSceneActionExecutorProperty record, @Param("example") PaasSceneActionExecutorPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int updateByPrimaryKeySelective(PaasSceneActionExecutorProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int updateByPrimaryKey(PaasSceneActionExecutorProperty record);
}