package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasInfraredBrandRemote;
import cn.xpms.paas.api.dao.generator.entity.PaasInfraredBrandRemoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasInfraredBrandRemoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    long countByExample(PaasInfraredBrandRemoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    int deleteByExample(PaasInfraredBrandRemoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    int insert(PaasInfraredBrandRemote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    int insertSelective(PaasInfraredBrandRemote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    List<PaasInfraredBrandRemote> selectByExampleWithRowbounds(PaasInfraredBrandRemoteExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    List<PaasInfraredBrandRemote> selectByExample(PaasInfraredBrandRemoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    PaasInfraredBrandRemote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasInfraredBrandRemote record, @Param("example") PaasInfraredBrandRemoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    int updateByExample(@Param("record") PaasInfraredBrandRemote record, @Param("example") PaasInfraredBrandRemoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    int updateByPrimaryKeySelective(PaasInfraredBrandRemote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_infrared_brand_remote
     *
     * @mbg.generated Wed Dec 02 10:54:15 CST 2020
     */
    int updateByPrimaryKey(PaasInfraredBrandRemote record);
}