package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasDeviceCategory;
import cn.xpms.paas.api.dao.generator.entity.PaasDeviceCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasDeviceCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    long countByExample(PaasDeviceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    int deleteByExample(PaasDeviceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    int insert(PaasDeviceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    int insertSelective(PaasDeviceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    List<PaasDeviceCategory> selectByExampleWithRowbounds(PaasDeviceCategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    List<PaasDeviceCategory> selectByExample(PaasDeviceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    PaasDeviceCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasDeviceCategory record, @Param("example") PaasDeviceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    int updateByExample(@Param("record") PaasDeviceCategory record, @Param("example") PaasDeviceCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    int updateByPrimaryKeySelective(PaasDeviceCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_category
     *
     * @mbg.generated Tue Jan 12 09:56:01 CST 2021
     */
    int updateByPrimaryKey(PaasDeviceCategory record);
}