package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationConditionDisplay;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationConditionDisplayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationConditionDisplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    long countByExample(PaasAutomationConditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int deleteByExample(PaasAutomationConditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int insert(PaasAutomationConditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int insertSelective(PaasAutomationConditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    List<PaasAutomationConditionDisplay> selectByExampleWithRowbounds(PaasAutomationConditionDisplayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    List<PaasAutomationConditionDisplay> selectByExample(PaasAutomationConditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    PaasAutomationConditionDisplay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasAutomationConditionDisplay record, @Param("example") PaasAutomationConditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int updateByExample(@Param("record") PaasAutomationConditionDisplay record, @Param("example") PaasAutomationConditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int updateByPrimaryKeySelective(PaasAutomationConditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int updateByPrimaryKey(PaasAutomationConditionDisplay record);
}