package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplateActionExecutor;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplateActionExecutorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationTemplateActionExecutorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    long countByExample(PaasAutomationTemplateActionExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    int deleteByExample(PaasAutomationTemplateActionExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    int insert(PaasAutomationTemplateActionExecutor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    int insertSelective(PaasAutomationTemplateActionExecutor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    List<PaasAutomationTemplateActionExecutor> selectByExampleWithRowbounds(PaasAutomationTemplateActionExecutorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    List<PaasAutomationTemplateActionExecutor> selectByExample(PaasAutomationTemplateActionExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    PaasAutomationTemplateActionExecutor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasAutomationTemplateActionExecutor record, @Param("example") PaasAutomationTemplateActionExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    int updateByExample(@Param("record") PaasAutomationTemplateActionExecutor record, @Param("example") PaasAutomationTemplateActionExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    int updateByPrimaryKeySelective(PaasAutomationTemplateActionExecutor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_action_executor
     *
     * @mbg.generated Fri Jan 29 16:21:59 CST 2021
     */
    int updateByPrimaryKey(PaasAutomationTemplateActionExecutor record);
}