package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationActionExecutorProperty;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationActionExecutorPropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationActionExecutorPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    long countByExample(PaasAutomationActionExecutorPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int deleteByExample(PaasAutomationActionExecutorPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int insert(PaasAutomationActionExecutorProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int insertSelective(PaasAutomationActionExecutorProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    List<PaasAutomationActionExecutorProperty> selectByExampleWithRowbounds(PaasAutomationActionExecutorPropertyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    List<PaasAutomationActionExecutorProperty> selectByExample(PaasAutomationActionExecutorPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    PaasAutomationActionExecutorProperty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasAutomationActionExecutorProperty record, @Param("example") PaasAutomationActionExecutorPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int updateByExample(@Param("record") PaasAutomationActionExecutorProperty record, @Param("example") PaasAutomationActionExecutorPropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int updateByPrimaryKeySelective(PaasAutomationActionExecutorProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_action_executor_property
     *
     * @mbg.generated Fri Dec 18 11:54:50 CST 2020
     */
    int updateByPrimaryKey(PaasAutomationActionExecutorProperty record);
}