package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasVoiceBrand;
import cn.xpms.paas.api.dao.generator.entity.PaasVoiceBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasVoiceBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasVoiceBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasVoiceBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasVoiceBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasVoiceBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasVoiceBrand> selectByExampleWithRowbounds(PaasVoiceBrandExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasVoiceBrand> selectByExample(PaasVoiceBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasVoiceBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasVoiceBrand record, @Param("example") PaasVoiceBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasVoiceBrand record, @Param("example") PaasVoiceBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasVoiceBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_brand
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasVoiceBrand record);
}