package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasMaintenanceTaskRoom;
import cn.xpms.paas.api.dao.generator.entity.PaasMaintenanceTaskRoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasMaintenanceTaskRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasMaintenanceTaskRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasMaintenanceTaskRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasMaintenanceTaskRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasMaintenanceTaskRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasMaintenanceTaskRoom> selectByExampleWithRowbounds(PaasMaintenanceTaskRoomExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasMaintenanceTaskRoom> selectByExample(PaasMaintenanceTaskRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasMaintenanceTaskRoom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasMaintenanceTaskRoom record, @Param("example") PaasMaintenanceTaskRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasMaintenanceTaskRoom record, @Param("example") PaasMaintenanceTaskRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasMaintenanceTaskRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_maintenance_task_room
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasMaintenanceTaskRoom record);
}