package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasDeviceInfoFunction;
import cn.xpms.paas.api.dao.generator.entity.PaasDeviceInfoFunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasDeviceInfoFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    long countByExample(PaasDeviceInfoFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int deleteByExample(PaasDeviceInfoFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int insert(PaasDeviceInfoFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int insertSelective(PaasDeviceInfoFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    List<PaasDeviceInfoFunction> selectByExampleWithRowbounds(PaasDeviceInfoFunctionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    List<PaasDeviceInfoFunction> selectByExample(PaasDeviceInfoFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    PaasDeviceInfoFunction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasDeviceInfoFunction record, @Param("example") PaasDeviceInfoFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int updateByExample(@Param("record") PaasDeviceInfoFunction record, @Param("example") PaasDeviceInfoFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int updateByPrimaryKeySelective(PaasDeviceInfoFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_device_info_function
     *
     * @mbg.generated Thu Jan 07 10:21:46 CST 2021
     */
    int updateByPrimaryKey(PaasDeviceInfoFunction record);
}