package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplateAutomation;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplateAutomationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationTemplateAutomationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    long countByExample(PaasAutomationTemplateAutomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    int deleteByExample(PaasAutomationTemplateAutomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    int insert(PaasAutomationTemplateAutomation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    int insertSelective(PaasAutomationTemplateAutomation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    List<PaasAutomationTemplateAutomation> selectByExampleWithRowbounds(PaasAutomationTemplateAutomationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    List<PaasAutomationTemplateAutomation> selectByExample(PaasAutomationTemplateAutomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    PaasAutomationTemplateAutomation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasAutomationTemplateAutomation record, @Param("example") PaasAutomationTemplateAutomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    int updateByExample(@Param("record") PaasAutomationTemplateAutomation record, @Param("example") PaasAutomationTemplateAutomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    int updateByPrimaryKeySelective(PaasAutomationTemplateAutomation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_automation
     *
     * @mbg.generated Thu Dec 31 09:16:07 CST 2020
     */
    int updateByPrimaryKey(PaasAutomationTemplateAutomation record);
}