package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationScene;
import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationSceneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasCustomAutomationSceneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    long countByExample(PaasCustomAutomationSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int deleteByExample(PaasCustomAutomationSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int insert(PaasCustomAutomationScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int insertSelective(PaasCustomAutomationScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    List<PaasCustomAutomationScene> selectByExampleWithRowbounds(PaasCustomAutomationSceneExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    List<PaasCustomAutomationScene> selectByExample(PaasCustomAutomationSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    PaasCustomAutomationScene selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasCustomAutomationScene record, @Param("example") PaasCustomAutomationSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByExample(@Param("record") PaasCustomAutomationScene record, @Param("example") PaasCustomAutomationSceneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByPrimaryKeySelective(PaasCustomAutomationScene record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_scene
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByPrimaryKey(PaasCustomAutomationScene record);
}