package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationTemplate;
import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasCustomAutomationTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    long countByExample(PaasCustomAutomationTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    int deleteByExample(PaasCustomAutomationTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    int insert(PaasCustomAutomationTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    int insertSelective(PaasCustomAutomationTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    List<PaasCustomAutomationTemplate> selectByExampleWithRowbounds(PaasCustomAutomationTemplateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    List<PaasCustomAutomationTemplate> selectByExample(PaasCustomAutomationTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    PaasCustomAutomationTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasCustomAutomationTemplate record, @Param("example") PaasCustomAutomationTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    int updateByExample(@Param("record") PaasCustomAutomationTemplate record, @Param("example") PaasCustomAutomationTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    int updateByPrimaryKeySelective(PaasCustomAutomationTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_template
     *
     * @mbg.generated Wed Apr 14 10:55:22 CST 2021
     */
    int updateByPrimaryKey(PaasCustomAutomationTemplate record);
}