package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasConstructionTemplateInfraredDevice;
import cn.xpms.paas.api.dao.generator.entity.PaasConstructionTemplateInfraredDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasConstructionTemplateInfraredDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasConstructionTemplateInfraredDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasConstructionTemplateInfraredDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasConstructionTemplateInfraredDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasConstructionTemplateInfraredDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasConstructionTemplateInfraredDevice> selectByExampleWithRowbounds(PaasConstructionTemplateInfraredDeviceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasConstructionTemplateInfraredDevice> selectByExample(PaasConstructionTemplateInfraredDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasConstructionTemplateInfraredDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasConstructionTemplateInfraredDevice record, @Param("example") PaasConstructionTemplateInfraredDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasConstructionTemplateInfraredDevice record, @Param("example") PaasConstructionTemplateInfraredDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasConstructionTemplateInfraredDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_infrared_device
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasConstructionTemplateInfraredDevice record);
}