package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplateConditionDisplay;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplateConditionDisplayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationTemplateConditionDisplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    long countByExample(PaasAutomationTemplateConditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int deleteByExample(PaasAutomationTemplateConditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int insert(PaasAutomationTemplateConditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int insertSelective(PaasAutomationTemplateConditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    List<PaasAutomationTemplateConditionDisplay> selectByExampleWithRowbounds(PaasAutomationTemplateConditionDisplayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    List<PaasAutomationTemplateConditionDisplay> selectByExample(PaasAutomationTemplateConditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    PaasAutomationTemplateConditionDisplay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasAutomationTemplateConditionDisplay record, @Param("example") PaasAutomationTemplateConditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int updateByExample(@Param("record") PaasAutomationTemplateConditionDisplay record, @Param("example") PaasAutomationTemplateConditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int updateByPrimaryKeySelective(PaasAutomationTemplateConditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_condition_display
     *
     * @mbg.generated Thu Jan 07 09:13:37 CST 2021
     */
    int updateByPrimaryKey(PaasAutomationTemplateConditionDisplay record);
}