package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasConstructionTemplatePosition;
import cn.xpms.paas.api.dao.generator.entity.PaasConstructionTemplatePositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasConstructionTemplatePositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasConstructionTemplatePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasConstructionTemplatePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasConstructionTemplatePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasConstructionTemplatePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasConstructionTemplatePosition> selectByExampleWithRowbounds(PaasConstructionTemplatePositionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasConstructionTemplatePosition> selectByExample(PaasConstructionTemplatePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasConstructionTemplatePosition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasConstructionTemplatePosition record, @Param("example") PaasConstructionTemplatePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasConstructionTemplatePosition record, @Param("example") PaasConstructionTemplatePositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasConstructionTemplatePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_construction_template_position
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasConstructionTemplatePosition record);
}