package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasSceneTemplateAction;
import cn.xpms.paas.api.dao.generator.entity.PaasSceneTemplateActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasSceneTemplateActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    long countByExample(PaasSceneTemplateActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    int deleteByExample(PaasSceneTemplateActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    int insert(PaasSceneTemplateAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    int insertSelective(PaasSceneTemplateAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    List<PaasSceneTemplateAction> selectByExampleWithRowbounds(PaasSceneTemplateActionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    List<PaasSceneTemplateAction> selectByExample(PaasSceneTemplateActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    PaasSceneTemplateAction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasSceneTemplateAction record, @Param("example") PaasSceneTemplateActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    int updateByExample(@Param("record") PaasSceneTemplateAction record, @Param("example") PaasSceneTemplateActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    int updateByPrimaryKeySelective(PaasSceneTemplateAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_template_action
     *
     * @mbg.generated Mon Dec 28 10:14:52 CST 2020
     */
    int updateByPrimaryKey(PaasSceneTemplateAction record);
}