package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomation;
import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasCustomAutomationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    long countByExample(PaasCustomAutomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int deleteByExample(PaasCustomAutomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int insert(PaasCustomAutomation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int insertSelective(PaasCustomAutomation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    List<PaasCustomAutomation> selectByExampleWithRowbounds(PaasCustomAutomationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    List<PaasCustomAutomation> selectByExample(PaasCustomAutomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    PaasCustomAutomation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasCustomAutomation record, @Param("example") PaasCustomAutomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByExample(@Param("record") PaasCustomAutomation record, @Param("example") PaasCustomAutomationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByPrimaryKeySelective(PaasCustomAutomation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByPrimaryKey(PaasCustomAutomation record);
}