package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasSceneAction;
import cn.xpms.paas.api.dao.generator.entity.PaasSceneActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasSceneActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    long countByExample(PaasSceneActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    int deleteByExample(PaasSceneActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    int insert(PaasSceneAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    int insertSelective(PaasSceneAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    List<PaasSceneAction> selectByExampleWithRowbounds(PaasSceneActionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    List<PaasSceneAction> selectByExample(PaasSceneActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    PaasSceneAction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasSceneAction record, @Param("example") PaasSceneActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    int updateByExample(@Param("record") PaasSceneAction record, @Param("example") PaasSceneActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    int updateByPrimaryKeySelective(PaasSceneAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_scene_action
     *
     * @mbg.generated Tue Dec 15 14:46:55 CST 2020
     */
    int updateByPrimaryKey(PaasSceneAction record);
}