package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationPreconditionDisplay;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationPreconditionDisplayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationPreconditionDisplayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    long countByExample(PaasAutomationPreconditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    int deleteByExample(PaasAutomationPreconditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    int insert(PaasAutomationPreconditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    int insertSelective(PaasAutomationPreconditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    List<PaasAutomationPreconditionDisplay> selectByExampleWithRowbounds(PaasAutomationPreconditionDisplayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    List<PaasAutomationPreconditionDisplay> selectByExample(PaasAutomationPreconditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    PaasAutomationPreconditionDisplay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasAutomationPreconditionDisplay record, @Param("example") PaasAutomationPreconditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    int updateByExample(@Param("record") PaasAutomationPreconditionDisplay record, @Param("example") PaasAutomationPreconditionDisplayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    int updateByPrimaryKeySelective(PaasAutomationPreconditionDisplay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_precondition_display
     *
     * @mbg.generated Thu Dec 17 17:05:20 CST 2020
     */
    int updateByPrimaryKey(PaasAutomationPreconditionDisplay record);
}