package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasLocationInfo;
import cn.xpms.paas.api.dao.generator.entity.PaasLocationInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasLocationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasLocationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasLocationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasLocationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasLocationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasLocationInfo> selectByExampleWithRowbounds(PaasLocationInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasLocationInfo> selectByExample(PaasLocationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasLocationInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasLocationInfo record, @Param("example") PaasLocationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasLocationInfo record, @Param("example") PaasLocationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasLocationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_location_info
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasLocationInfo record);
}