package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasProjectInfo;
import cn.xpms.paas.api.dao.generator.entity.PaasProjectInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasProjectInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    long countByExample(PaasProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    int deleteByExample(PaasProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    int insert(PaasProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    int insertSelective(PaasProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    List<PaasProjectInfo> selectByExampleWithRowbounds(PaasProjectInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    List<PaasProjectInfo> selectByExample(PaasProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    PaasProjectInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasProjectInfo record, @Param("example") PaasProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    int updateByExample(@Param("record") PaasProjectInfo record, @Param("example") PaasProjectInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    int updateByPrimaryKeySelective(PaasProjectInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_info
     *
     * @mbg.generated Tue Dec 08 09:58:12 CST 2020
     */
    int updateByPrimaryKey(PaasProjectInfo record);
}