package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasVoiceRoomRelation;
import cn.xpms.paas.api.dao.generator.entity.PaasVoiceRoomRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasVoiceRoomRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    long countByExample(PaasVoiceRoomRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    int deleteByExample(PaasVoiceRoomRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    int insert(PaasVoiceRoomRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    int insertSelective(PaasVoiceRoomRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    List<PaasVoiceRoomRelation> selectByExampleWithRowbounds(PaasVoiceRoomRelationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    List<PaasVoiceRoomRelation> selectByExample(PaasVoiceRoomRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    PaasVoiceRoomRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasVoiceRoomRelation record, @Param("example") PaasVoiceRoomRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    int updateByExample(@Param("record") PaasVoiceRoomRelation record, @Param("example") PaasVoiceRoomRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    int updateByPrimaryKeySelective(PaasVoiceRoomRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_room_relation
     *
     * @mbg.generated Mon Dec 21 11:57:30 CST 2020
     */
    int updateByPrimaryKey(PaasVoiceRoomRelation record);
}