package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationType;
import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasCustomAutomationTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    long countByExample(PaasCustomAutomationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int deleteByExample(PaasCustomAutomationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int insert(PaasCustomAutomationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int insertSelective(PaasCustomAutomationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    List<PaasCustomAutomationType> selectByExampleWithRowbounds(PaasCustomAutomationTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    List<PaasCustomAutomationType> selectByExample(PaasCustomAutomationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    PaasCustomAutomationType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasCustomAutomationType record, @Param("example") PaasCustomAutomationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByExample(@Param("record") PaasCustomAutomationType record, @Param("example") PaasCustomAutomationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByPrimaryKeySelective(PaasCustomAutomationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_type
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByPrimaryKey(PaasCustomAutomationType record);
}