package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasRoomTemplate;
import cn.xpms.paas.api.dao.generator.entity.PaasRoomTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasRoomTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    long countByExample(PaasRoomTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    int deleteByExample(PaasRoomTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    int insert(PaasRoomTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    int insertSelective(PaasRoomTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    List<PaasRoomTemplate> selectByExampleWithRowbounds(PaasRoomTemplateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    List<PaasRoomTemplate> selectByExample(PaasRoomTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    PaasRoomTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasRoomTemplate record, @Param("example") PaasRoomTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    int updateByExample(@Param("record") PaasRoomTemplate record, @Param("example") PaasRoomTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    int updateByPrimaryKeySelective(PaasRoomTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_template
     *
     * @mbg.generated Thu Jan 07 16:21:59 CST 2021
     */
    int updateByPrimaryKey(PaasRoomTemplate record);
}