package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasDoorLockPassword;
import cn.xpms.paas.api.dao.generator.entity.PaasDoorLockPasswordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasDoorLockPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    long countByExample(PaasDoorLockPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    int deleteByExample(PaasDoorLockPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    int insert(PaasDoorLockPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    int insertSelective(PaasDoorLockPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    List<PaasDoorLockPassword> selectByExampleWithRowbounds(PaasDoorLockPasswordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    List<PaasDoorLockPassword> selectByExample(PaasDoorLockPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    PaasDoorLockPassword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasDoorLockPassword record, @Param("example") PaasDoorLockPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    int updateByExample(@Param("record") PaasDoorLockPassword record, @Param("example") PaasDoorLockPasswordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    int updateByPrimaryKeySelective(PaasDoorLockPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_door_lock_password
     *
     * @mbg.generated Mon Jan 04 15:40:32 CST 2021
     */
    int updateByPrimaryKey(PaasDoorLockPassword record);
}