package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationCondition;
import cn.xpms.paas.api.dao.generator.entity.PaasCustomAutomationConditionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasCustomAutomationConditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    long countByExample(PaasCustomAutomationConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int deleteByExample(PaasCustomAutomationConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int insert(PaasCustomAutomationCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int insertSelective(PaasCustomAutomationCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    List<PaasCustomAutomationCondition> selectByExampleWithRowbounds(PaasCustomAutomationConditionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    List<PaasCustomAutomationCondition> selectByExample(PaasCustomAutomationConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    PaasCustomAutomationCondition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") PaasCustomAutomationCondition record, @Param("example") PaasCustomAutomationConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByExample(@Param("record") PaasCustomAutomationCondition record, @Param("example") PaasCustomAutomationConditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByPrimaryKeySelective(PaasCustomAutomationCondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_custom_automation_condition
     *
     * @mbg.generated Tue Jan 12 14:46:21 CST 2021
     */
    int updateByPrimaryKey(PaasCustomAutomationCondition record);
}