package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasApiToken;
import cn.xpms.paas.api.dao.generator.entity.PaasApiTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasApiTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasApiTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasApiTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasApiToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasApiToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasApiToken> selectByExampleWithRowbounds(PaasApiTokenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasApiToken> selectByExample(PaasApiTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasApiToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasApiToken record, @Param("example") PaasApiTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasApiToken record, @Param("example") PaasApiTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasApiToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_api_token
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasApiToken record);
}