package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasRoomInfo;
import cn.xpms.paas.api.dao.generator.entity.PaasRoomInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasRoomInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    long countByExample(PaasRoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    int deleteByExample(PaasRoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    int insert(PaasRoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    int insertSelective(PaasRoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    List<PaasRoomInfo> selectByExampleWithRowbounds(PaasRoomInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    List<PaasRoomInfo> selectByExample(PaasRoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    PaasRoomInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasRoomInfo record, @Param("example") PaasRoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    int updateByExample(@Param("record") PaasRoomInfo record, @Param("example") PaasRoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    int updateByPrimaryKeySelective(PaasRoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_room_info
     *
     * @mbg.generated Wed Dec 02 15:31:47 CST 2020
     */
    int updateByPrimaryKey(PaasRoomInfo record);
}