package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasProjectVoiceAuthorization;
import cn.xpms.paas.api.dao.generator.entity.PaasProjectVoiceAuthorizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasProjectVoiceAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    long countByExample(PaasProjectVoiceAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByExample(PaasProjectVoiceAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insert(PaasProjectVoiceAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int insertSelective(PaasProjectVoiceAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasProjectVoiceAuthorization> selectByExampleWithRowbounds(PaasProjectVoiceAuthorizationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    List<PaasProjectVoiceAuthorization> selectByExample(PaasProjectVoiceAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    PaasProjectVoiceAuthorization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasProjectVoiceAuthorization record, @Param("example") PaasProjectVoiceAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByExample(@Param("record") PaasProjectVoiceAuthorization record, @Param("example") PaasProjectVoiceAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKeySelective(PaasProjectVoiceAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_project_voice_authorization
     *
     * @mbg.generated Tue Dec 01 11:13:32 CST 2020
     */
    int updateByPrimaryKey(PaasProjectVoiceAuthorization record);
}