package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasVoiceThirdPartyAuthorization;
import cn.xpms.paas.api.dao.generator.entity.PaasVoiceThirdPartyAuthorizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasVoiceThirdPartyAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    long countByExample(PaasVoiceThirdPartyAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    int deleteByExample(PaasVoiceThirdPartyAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    int insert(PaasVoiceThirdPartyAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    int insertSelective(PaasVoiceThirdPartyAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    List<PaasVoiceThirdPartyAuthorization> selectByExampleWithRowbounds(PaasVoiceThirdPartyAuthorizationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    List<PaasVoiceThirdPartyAuthorization> selectByExample(PaasVoiceThirdPartyAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    PaasVoiceThirdPartyAuthorization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasVoiceThirdPartyAuthorization record, @Param("example") PaasVoiceThirdPartyAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    int updateByExample(@Param("record") PaasVoiceThirdPartyAuthorization record, @Param("example") PaasVoiceThirdPartyAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    int updateByPrimaryKeySelective(PaasVoiceThirdPartyAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_voice_third_party_authorization
     *
     * @mbg.generated Mon Dec 21 11:59:25 CST 2020
     */
    int updateByPrimaryKey(PaasVoiceThirdPartyAuthorization record);
}