package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationInfo;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    long countByExample(PaasAutomationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    int deleteByExample(PaasAutomationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    int insert(PaasAutomationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    int insertSelective(PaasAutomationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    List<PaasAutomationInfo> selectByExampleWithRowbounds(PaasAutomationInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    List<PaasAutomationInfo> selectByExample(PaasAutomationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    PaasAutomationInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasAutomationInfo record, @Param("example") PaasAutomationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    int updateByExample(@Param("record") PaasAutomationInfo record, @Param("example") PaasAutomationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    int updateByPrimaryKeySelective(PaasAutomationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_info
     *
     * @mbg.generated Thu Dec 17 10:42:38 CST 2020
     */
    int updateByPrimaryKey(PaasAutomationInfo record);
}