package cn.xpms.paas.api.dao.generator.repository;

import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplatePrecondition;
import cn.xpms.paas.api.dao.generator.entity.PaasAutomationTemplatePreconditionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PaasAutomationTemplatePreconditionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    long countByExample(PaasAutomationTemplatePreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int deleteByExample(PaasAutomationTemplatePreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int insert(PaasAutomationTemplatePrecondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int insertSelective(PaasAutomationTemplatePrecondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    List<PaasAutomationTemplatePrecondition> selectByExampleWithRowbounds(PaasAutomationTemplatePreconditionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    List<PaasAutomationTemplatePrecondition> selectByExample(PaasAutomationTemplatePreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    PaasAutomationTemplatePrecondition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") PaasAutomationTemplatePrecondition record, @Param("example") PaasAutomationTemplatePreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByExample(@Param("record") PaasAutomationTemplatePrecondition record, @Param("example") PaasAutomationTemplatePreconditionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByPrimaryKeySelective(PaasAutomationTemplatePrecondition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paas_automation_template_precondition
     *
     * @mbg.generated Tue Dec 29 11:03:11 CST 2020
     */
    int updateByPrimaryKey(PaasAutomationTemplatePrecondition record);
}