package cn.xpms.system.system.dao.generator.repository;

import cn.xpms.system.system.dao.generator.entity.SysRole2right;
import cn.xpms.system.system.dao.generator.entity.SysRole2rightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface SysRole2rightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    long countByExample(SysRole2rightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int deleteByExample(SysRole2rightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int insert(SysRole2right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int insertSelective(SysRole2right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    List<SysRole2right> selectByExampleWithRowbounds(SysRole2rightExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    List<SysRole2right> selectByExample(SysRole2rightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    SysRole2right selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysRole2right record, @Param("example") SysRole2rightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByExample(@Param("record") SysRole2right record, @Param("example") SysRole2rightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByPrimaryKeySelective(SysRole2right record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2right
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByPrimaryKey(SysRole2right record);
}