package cn.xpms.system.system.dao.generator.repository;

import cn.xpms.system.system.dao.generator.entity.SysRole2subsys;
import cn.xpms.system.system.dao.generator.entity.SysRole2subsysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface SysRole2subsysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    long countByExample(SysRole2subsysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int deleteByExample(SysRole2subsysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int insert(SysRole2subsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int insertSelective(SysRole2subsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    List<SysRole2subsys> selectByExampleWithRowbounds(SysRole2subsysExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    List<SysRole2subsys> selectByExample(SysRole2subsysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    SysRole2subsys selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysRole2subsys record, @Param("example") SysRole2subsysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByExample(@Param("record") SysRole2subsys record, @Param("example") SysRole2subsysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByPrimaryKeySelective(SysRole2subsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2subsys
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByPrimaryKey(SysRole2subsys record);
}