package cn.xpms.system.system.dao.generator.repository;

import cn.xpms.system.system.dao.generator.entity.SysSubsysConfig;
import cn.xpms.system.system.dao.generator.entity.SysSubsysConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface SysSubsysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    long countByExample(SysSubsysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int deleteByExample(SysSubsysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int insert(SysSubsysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int insertSelective(SysSubsysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    List<SysSubsysConfig> selectByExampleWithRowbounds(SysSubsysConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    List<SysSubsysConfig> selectByExample(SysSubsysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    SysSubsysConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysSubsysConfig record, @Param("example") SysSubsysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByExample(@Param("record") SysSubsysConfig record, @Param("example") SysSubsysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByPrimaryKeySelective(SysSubsysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_subsys_config
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByPrimaryKey(SysSubsysConfig record);
}