package cn.xpms.system.system.dao.generator.repository;

import cn.xpms.system.system.dao.generator.entity.SysUser2role;
import cn.xpms.system.system.dao.generator.entity.SysUser2roleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface SysUser2roleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    long countByExample(SysUser2roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int deleteByExample(SysUser2roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int insert(SysUser2role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int insertSelective(SysUser2role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    List<SysUser2role> selectByExampleWithRowbounds(SysUser2roleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    List<SysUser2role> selectByExample(SysUser2roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    SysUser2role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysUser2role record, @Param("example") SysUser2roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByExample(@Param("record") SysUser2role record, @Param("example") SysUser2roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByPrimaryKeySelective(SysUser2role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbg.generated Wed Nov 25 11:55:57 CST 2020
     */
    int updateByPrimaryKey(SysUser2role record);
}