package cn.xpms.third.security.dao.generator.repository;

import cn.xpms.third.security.dao.generator.entity.PublicSecuritySysConfig;
import cn.xpms.third.security.dao.generator.entity.PublicSecuritySysConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PublicSecuritySysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    long countByExample(PublicSecuritySysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int deleteByExample(PublicSecuritySysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int insert(PublicSecuritySysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int insertSelective(PublicSecuritySysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    List<PublicSecuritySysConfig> selectByExampleWithRowbounds(PublicSecuritySysConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    List<PublicSecuritySysConfig> selectByExample(PublicSecuritySysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    PublicSecuritySysConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") PublicSecuritySysConfig record, @Param("example") PublicSecuritySysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByExample(@Param("record") PublicSecuritySysConfig record, @Param("example") PublicSecuritySysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByPrimaryKeySelective(PublicSecuritySysConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_sys_config
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByPrimaryKey(PublicSecuritySysConfig record);
}