package cn.xpms.third.security.dao.generator.repository;

import cn.xpms.third.security.dao.generator.entity.PublicSecurityUploadRecord;
import cn.xpms.third.security.dao.generator.entity.PublicSecurityUploadRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PublicSecurityUploadRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    long countByExample(PublicSecurityUploadRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int deleteByExample(PublicSecurityUploadRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int insert(PublicSecurityUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int insertSelective(PublicSecurityUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    List<PublicSecurityUploadRecord> selectByExampleWithRowbounds(PublicSecurityUploadRecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    List<PublicSecurityUploadRecord> selectByExample(PublicSecurityUploadRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    PublicSecurityUploadRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") PublicSecurityUploadRecord record, @Param("example") PublicSecurityUploadRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByExample(@Param("record") PublicSecurityUploadRecord record, @Param("example") PublicSecurityUploadRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByPrimaryKeySelective(PublicSecurityUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_record
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByPrimaryKey(PublicSecurityUploadRecord record);
}