package cn.xpms.third.security.dao.generator.repository;

import cn.xpms.third.security.dao.generator.entity.PublicSecurityUploadInfo;
import cn.xpms.third.security.dao.generator.entity.PublicSecurityUploadInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PublicSecurityUploadInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    long countByExample(PublicSecurityUploadInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    int deleteByExample(PublicSecurityUploadInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    int insert(PublicSecurityUploadInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    int insertSelective(PublicSecurityUploadInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    List<PublicSecurityUploadInfo> selectByExampleWithRowbounds(PublicSecurityUploadInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    List<PublicSecurityUploadInfo> selectByExample(PublicSecurityUploadInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    PublicSecurityUploadInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") PublicSecurityUploadInfo record, @Param("example") PublicSecurityUploadInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    int updateByExample(@Param("record") PublicSecurityUploadInfo record, @Param("example") PublicSecurityUploadInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    int updateByPrimaryKeySelective(PublicSecurityUploadInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_upload_info
     *
     * @mbg.generated Sat Nov 14 14:49:30 CST 2020
     */
    int updateByPrimaryKey(PublicSecurityUploadInfo record);
}