package cn.xpms.third.security.dao.generator.repository;

import cn.xpms.third.security.dao.generator.entity.PublicSecurityDict;
import cn.xpms.third.security.dao.generator.entity.PublicSecurityDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PublicSecurityDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    long countByExample(PublicSecurityDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int deleteByExample(PublicSecurityDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int insert(PublicSecurityDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int insertSelective(PublicSecurityDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    List<PublicSecurityDict> selectByExampleWithRowbounds(PublicSecurityDictExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    List<PublicSecurityDict> selectByExample(PublicSecurityDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    PublicSecurityDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") PublicSecurityDict record, @Param("example") PublicSecurityDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByExample(@Param("record") PublicSecurityDict record, @Param("example") PublicSecurityDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByPrimaryKeySelective(PublicSecurityDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_dict
     *
     * @mbg.generated Wed Nov 11 16:43:54 CST 2020
     */
    int updateByPrimaryKey(PublicSecurityDict record);
}