package cn.xpms.third.security.dao.generator.repository;

import cn.xpms.third.security.dao.generator.entity.PublicSecurityConfig;
import cn.xpms.third.security.dao.generator.entity.PublicSecurityConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PublicSecurityConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    long countByExample(PublicSecurityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    int deleteByExample(PublicSecurityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    int insert(PublicSecurityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    int insertSelective(PublicSecurityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    List<PublicSecurityConfig> selectByExampleWithRowbounds(PublicSecurityConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    List<PublicSecurityConfig> selectByExample(PublicSecurityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    PublicSecurityConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") PublicSecurityConfig record, @Param("example") PublicSecurityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    int updateByExample(@Param("record") PublicSecurityConfig record, @Param("example") PublicSecurityConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    int updateByPrimaryKeySelective(PublicSecurityConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_security_config
     *
     * @mbg.generated Fri Nov 13 16:59:22 CST 2020
     */
    int updateByPrimaryKey(PublicSecurityConfig record);
}